### PR TITLE
compilation broken with CONFIG_MODULE

### PR DESCRIPTION
**Pull request by adrenogamer**
remove odd EXPORT_SYMBOL
rename EXPORT_SYMBOL to EXPORT_SYMBOL_GPL

### CODE REVIEW

**Comment by ShadowReaper1** [comment]
Is this tested and working?

**Comment by adrenogamer** [comment]
Yes. This tested with configs: 
CONFIG_MODULE=y
CONFIG_MODULE_UNLOAD=y
CONFIG_MODULE_FORCE_LOAD=y
CONFIG_MODULE_FORCE_UNLOAD=y
Compiled without errors and works perfectly.

**Comment by audahadi** [comment]
https://github.com/kernel-hut/android_kernel_asus_msm8916/commit/d7f70e436ce44f395d0939d3b8737801fc47f254

This patch should work because for aosp defconfig before , I also build modules

**Comment by audahadi** [comment]
Can also revert this patch to simply solve that

https://github.com/kernel-hut/android_kernel_asus_msm8916/commit/0e5f82c5c701012df6ea7535ce99060036f5df70

**Pull request closed without merging**
